### PR TITLE
Allow fragment alias.

### PR DESCRIPTION
**Pull request by DylanPiercey**
Using "frag" makes this feel cheap.

### CODE REVIEW

**Comment by jquense** [comment]
"cheap"?

**Comment by DylanPiercey** [comment]
In the browser it is always refered to as fragment, by using a shorter name it just makes it feel unofficial to me. It's not a game changer, just ocd.

**Comment by jquense** [comment]
fair enough, let me just confirm that doesn't conflict with anything

**Comment by DylanPiercey** [comment]
@jquense what are your thoughts on compiling to an array of keyed nodes? We could prefix any existing keys that are direct children of the fragment. This way the react addon is not needed.

**Comment by jquense** [comment]
I tried that approach first but its not reliable, because you can't always statically determine what the key is for an element:

Besides I don't really mind having the addon; its not like it adds any actual overhead since it just requires from `react/lib`. Beyond that, this use case is really what that addon is for.

**Comment by DylanPiercey** [comment]
Any problems with this?

**Comment by jquense** [comment]
thanks

**Pull request merged**
